# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0010_auto_20171211_1501'),
        ('questions', '0003_question_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('questions', models.IntegerField(default=0)),
                ('answers', models.IntegerField(default=0)),
                ('solutions', models.IntegerField(default=0)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
